### ISSUE TITLE
Unnamed / anonymous structs not supported

### ISSUE THREAD

**Issue by N3xed** [reignofwebber/vscode-c-cpp-definition-generator#2]
![image](https://user-images.githubusercontent.com/11508388/59466442-a423e880-8e2d-11e9-9388-9dfa53b6b091.png)

Both commands do nothing, only "Cppext: generate source file from header file" reports an error.

**Comment by reignofwebber** [comment]
thanks for reporting this issue, I'll fix it in the next release

**Comment by reignofwebber** [comment]
this bug should be fixed in version 0.0.2
